### ISSUE TITLE
Games immediately running out of time

### ISSUE THREAD

**Issue by Kodykthx** [grompe/Drawception-ANBT#23]
http://puu.sh/qtVkr/04f5c8dfe9.png
http://puu.sh/qtVRk/9f037e1dca.png
Every game I go to it seems that I immediately run out of time?
I skip that game, it goes to sandbox (and says i'm out of time in sandbox?)
the only time i can actually do anything is when i'm placed on a describe panel (which i have to turn off the script first to do so anyways) it works fine without the script and i've tried turning off "
Confirm submitting if more than a minute is left (New canvas only)" which seemed like it would be linked to the problem, but it wasnt. Sorry if i'm missing something, I've never had this problem before.
everything works perfectly fine when i turn it off, but when i turn it back on every drawing panel is times up as soon as i enter it

**Comment by grompe** [comment]
ANBT can break when site gets layout updates, which just happened. It has been fixed now.
