### ISSUE TITLE
New Drawception favorite button breaks Like All and Reverse buttons

### ISSUE THREAD

**Issue by BertrandTheHealer** [grompe/Drawception-ANBT#26]
![image](https://user-images.githubusercontent.com/17074869/36739126-cf05dd4e-1ba4-11e8-9a1c-febf9be4bb20.png)

**Comment by BertrandTheHealer** [comment]
The Like All and Reverse buttons no longer appear next to the Favorite button on Drawception version 2.8.0. See my pull request [here](https://github.com/grompe/Drawception-ANBT/pull/25)

**Comment by grompe** [comment]
Fixed in 1.119.2018.03.
