### ISSUE TITLE
TypeError in new canvas in Android Firefox

### ISSUE THREAD

**Issue by BertrandTheHealer** [grompe/Drawception-ANBT#27]
After the latest update, the following error occurs whenever I attempt to do anything (draw, change color, skip, go back to homepage) in the new canvas, either sandbox or in game: ![screenshot_20180305-123513](https://user-images.githubusercontent.com/17074869/36995747-20db0b2c-2072-11e8-9677-b1af914629ef.png)
This doesn't happen in the desktop version of Firefox.

**Comment by grompe** [comment]
Ah, good job, Firefox:
https://github.com/progers/pathseg/commit/e629e014517d4b7047f051b61435b70565b1e1dd

Fixed for the next version.
